In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime
pd.options.display.float_format = '{:.2f}'.format
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import warnings
warnings.filterwarnings("ignore")

In [3]:
miami = pd.read_excel('c:/Users/denis/Desktop/Ironhack/ironhackLabs/Transportation/Users_Monthly.xlsx')

In [4]:
miami = miami[miami['UZA Name'] == 'Miami, FL']
miami = miami[miami['Agency'] == 'Miami-Dade Transit']
miami = miami.drop(['5 digit NTD ID', 'UZA', 'Unnamed: 226'], axis=1)
miami_grouped = miami.groupby('Modes').sum()

In [5]:
miami_grouped.head()

,JAN02,FEB02,MAR02,APR02,MAY02,JUN02,JUL02,AUG02,SEP02,OCT02,NOV02,DEC02,JAN03,FEB03,MAR03,APR03,MAY03,JUN03,JUL03,AUG03,SEP03,OCT03,NOV03,DEC03,JAN04,FEB04,MAR04,APR04,MAY04,JUN04,JUL04,AUG04,SEP04,OCT04,NOV04,DEC04,JAN05,FEB05,MAR05,APR05,MAY05,JUN05,JUL05,AUG05,SEP05,OCT05,NOV05,DEC05,JAN06,FEB06,MAR06,APR06,MAY06,JUN06,JUL06,AUG06,SEP06,OCT06,NOV06,DEC06,JAN07,FEB07,MAR07,APR07,MAY07,JUN07,JUL07,AUG07,SEP07,OCT07,NOV07,DEC07,JAN08,FEB08,MAR08,APR08,MAY08,JUN08,JUL08,AUG08,SEP08,OCT08,NOV08,DEC08,JAN09,FEB09,MAR09,APR09,MAY09,JUN09,JUL09,AUG09,SEP09,OCT09,NOV09,DEC09,JAN10,FEB10,MAR10,APR10,MAY10,JUN10,JUL10,AUG10,SEP10,OCT10,NOV10,DEC10,JAN11,FEB11,MAR11,APR11,MAY11,JUN11,JUL11,AUG11,SEP11,OCT11,NOV11,DEC11,JAN12,FEB12,MAR12,APR12,MAY12,JUN12,JUL12,AUG12,SEP12,OCT12,NOV12,DEC12,JAN13,FEB13,MAR13,APR13,MAY13,JUN13,JUL13,AUG13,SEP13,OCT13,NOV13,DEC13,JAN14,FEB14,MAR14,APR14,MAY14,JUN14,JUL14,AUG14,SEP14,OCT14,NOV14,DEC14,JAN15,FEB15,MAR15,APR15,MAY15,JUN15,JUL15,AUG15,SEP15,OCT15,NOV15,DEC15,JAN16,FEB16,MAR16,APR16,MAY16,JUN16,JUL16,AUG16,SEP16,OCT16,NOV16,DEC16,JAN17,FEB17,MAR17,APR17,MAY17,JUN17,JUL17,AUG17,SEP17,OCT17,NOV17,DEC17,JAN18,FEB18,MAR18,APR18,MAY18,JUN18,JUL18,AUG18,SEP18,OCT18,NOV18,DEC18,JAN19,FEB19,MAR19,APR19,MAY19,JUN19,JUL19,AUG19,SEP19,OCT19,NOV19,DEC19,JAN20
Modes,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Bus,5512260.00,5212070.00,5584941.00,5485658.00,5526653.00,4868326.00,5318877.00,5456934.00,5268803.00,5833271.00,5214391.00,5230387.00,5395806.00,5710527.00,6003891.00,5476479.00,5570370.00,5212207.00,5560537.00,5431215.00,5549182.00,5989423.00,5487946.00,5517526.00,6117990.00,6040880.00,6708846.00,6766912.00,6371456.00,6384199.00,6658227.00,6587799.00,7025682.00,7415853.00,6711378.00,6850814.00,6703209.00,6458778.00,7189671.00,6738174.00,7135949.00,6145300.00,6257652.00,6524011.00,6689814.00,6289358.00,7072014.00,7155858.00,7233774.00,6720318.00,7680650.00,6972300.00,7188801.00,7073119.00,6615189.00,7096612.00,7063309.00,7450511.00,7012951.00,6922286.00,7225204.00,6780075.00,7650948.00,6934652.00,7223046.00,6723085.00,6714140.00,7194214.00,7209981.00,7601166.00,7119785.00,7044371.00,7122390.00,7040637.00,7347587.00,7253804.00,7449306.00,7149288.00,7526448.00,7122809.00,7490700.00,7167867.00,6522939.00,6608908.00,6563369.00,6349957.00,6839145.00,7212702.00,6294428.00,5884426.00,6040944.00,6069316.00,6105713.00,6151678.00,5669250.00,5827925.00,5728052.00,5709910.00,6435598.00,6165876.00,6117790.00,5952186.00,5913496.00,6034112.00,6139651.00,6528026.00,6263925.00,6042965.00,6335200.00,6257210.00,6995622.00,6581303.00,6604376.00,6366584.00,6151452.00,6519037.00,6671320.00,6658055.00,6713595.00,6617842.00,6769561.00,6649619.00,7155078.00,6610528.00,6717198.00,6279352.00,6345294.00,6537294.00,6447207.00,7179884.00,6792950.00,6546516.00,6798921.00,6580295.00,6986983.00,6869106.00,6741668.00,6177871.00,6407429.00,6753419.00,6649205.00,7299170.00,6556720.00,6551544.00,6653350.00,6451457.00,6810455.00,6742944.00,6577085.00,6017396.00,6284522.00,6425908.00,6540101.00,6912922.00,6118467.00,6461736.00,6470575.00,5904204.00,6802031.00,6273258.00,6044299.00,5747574.00,5891889.00,5873269.00,5908391.00,6238588.00,5647039.00,5805733.00,5580707.00,5633914.00,5903862.00,5698145.00,5564241.00,5310256.00,5132849.00,5342292.00,5325486.00,5086790.00,5348172.00,5356637.00,5250895.00,5077884.00,5473080.00,5062054.00,5270187.00,4756582.00,4702824.00,4961922.00,3669995.00,4862999.00,4665625.00,4517054.00,4488710.00,4385530.00,4727366.00,4548340.00,4471727.00,4193031.00,4263154.00,4522253.00,4222242.00,4760815.00,4430104.00,4255258.00,4383467.00,4172464.00,4459521.00,4489953.00,4531181.00,4003475.00,4282876.00,4298350.00,4152847.00,4711873.00,4384054.00,4309412.00,4512320.00
Rail,1551952.00,1494895.00,1613905.00,1583007.00,1587454.00,1453326.00,1603810.00,1591425.00,1527310.00,1777054.00,1714024.00,1651569.00,1665143.00,1671374.00,1699954.00,1747261.00,1706395.00,1721018.00,1837857.00,1809905.00,1889655.00,1905094.00,1736004.00,1693102.00,1868931.00,1844918.00,2064335.00,2022192.00,2087918.00,2123075.00,2103294.00,2170690.00,2147603.00,2365618.00,2187580.00,2156588.00,2225823.00,2153950.00,2259151.00,2299201.00,2249773.00,2134386.00,2068514.00,2115370.00,2130634.00,1706959.00,2065192.00,2201521.00,2227493.00,2123775.00,2376973.00,2120811.00,2195174.00,2250495.00,2060099.00,2092822.00,2189193.00,2264315.00,2111826.00,2047906.00,2201673.00,2060509.00,2279585.00,2135256.00,2153081.00,2071396.00,2076103.00,2139699.00,2207266.00,2305904.00,2194663.00,2020055.00,2143571.00,2143541.00,2359474.00,2360301.00,2268108.00,2354573.00,2505415.00,2300810.00,2418481.00,2520809.00,2173219.00,2204733.00,2173665.00,2065714.00,2177326.00,2228031.00,2135393.00,2153360.00,2207309.00,2172373.00,2132689.00,2239391.00,2014557.00,2078200.00,2077222.00,1952029.00,2296938.00,2172725.00,2090303.00,2092152.00,2060240.00,2131313.00,2179703.00,2310450.00,2225604.00,2121848.00,2258556.00,2197389.00,2522145.00,2355348.00,2294204.00,2271091.00,2167265.00,2307494.00,2270500.00,2343957.00,2277215.00,2211556.00,2315825.00,2329307.00,2589145.00,2347233.00,2331207.00,2193530.00,2230245.00,2328112.00,2311201.00,2665913.00,2507924.00,2348999.00,2596625.00,2449703.00,2806110.00,2653097.00,2574643.00,2499848.00,2485634.00,2514668.00,2506651.00,2804084.00,2519180.00,2541577.00,2657070.00,2615484.00,2883651.00,2707152.00,2604122.00,2456900.00,2548964.00,2546990.00,2620572.00,2884778.00,2474957.00,2670710.00,2705423.00,2541763.00,2976362.00,2732863.00,2546864.00,2549806.00,2599414.00,2532937.00,2632324.00,2829731.00,2590463.00,2689207.00,2652106.00,2684835.00,3004914.00,2730235.00,2600804.00,2499250.00,2419202.00,2526461.00,2551980.00,2485714.00,2575946.00,2593729.00,2596426.00,2456729.00,2875479.00,2480237.00,2602676.00,2342276.00,2296892.00,2482258.00,1659776.00,2459887.00,2339407.00,2266138.00,2387698.00,2243688.00,2559857.00,2359926.00,2312610.00,2165986.00,2227842.00,2401199.00,2228593.00,2547758.00,2392127.00,2321043.00,2455423.00,2176618.00,2292665.00,2355142.00,2266242.00,2061284.00,2158972.00,2203431.00,2127605.00,2474400.00,2269080.00,2283760.00,2407817.00

In [6]:
miami_grouped = miami_grouped.T
miami_test = miami_grouped.reset_index()
miami_test = miami_test.rename(columns={"index": "Time"})

In [7]:
miami_test['Time'] = pd.to_datetime(miami_test['Time'], format='%b%y')
miami_test = miami_test.set_index(['Time'], drop=True)

In [8]:
miami_test.head()

Modes             Bus       Rail
Time
2002-01-01 5512260.00 1551952.00
2002-02-01 5212070.00 1494895.00
2002-03-01 5584941.00 1613905.00
2002-04-01 5485658.00 1583007.00
2002-05-01 5526653.00 1587454.00

In [9]:
mGDP = pd.read_csv('c:/Users/denis/Desktop/Ironhack/ironhackLabs/Transportation/GDPpercapita.csv')

In [10]:
mGDP['Time']= pd.to_datetime(mGDP['Time'], format='%Y')

In [11]:
mGDP

,Time,Personal income (thousands of dollars),Population,Per capita income
0,2002-01-01,67107084,2315747,28979
1,2003-01-01,69240316,2336070,29640
2,2004-01-01,74881769,2358684,31747
3,2005-01-01,81381738,2385872,34110
4,2006-01-01,89240479,2405911,37092
5,2007-01-01,92614163,2415576,38340
6,2008-01-01,93033991,2436062,38190
7,2009-01-01,85787430,2463943,34817
8,2010-01-01,95805838,2507065,38214
9,2011-01-01,100148724,2569856,38971
10,2012-01-01,103220841,2602184,39667
11,2013-01-01,103504316,2635640,39271
12,2014-01-01,111907652,2660389,42064
13,2015-01-01,119434694,2688156,44430
14,2016-01-01,119576094,2722574,43920
15,2017-01-01,131241442,2744878,47813
16,2018-01-01,138138976,2761581,50022

In [59]:
# mGDP.index = pd.Index(['Personal Income','Population','Per Capita income'],name='Time')
# mgdp = mGDP.T
# mgdp = mgdp.drop(['Description'])
# mgdp = mgdp.drop(['a'], axis=1)

In [64]:
# # mGDP.reset_index()

# miami_grouped = mGDP.T
# miami_test = miami_grouped.reset_index()
# miami_test = miami_test.rename(columns={"index": "Time"})

In [106]:
# mgdp = miami_test.rename(columns={0: "a", 1: "Population", 2:"Per Capita Income"})

In [107]:
# mgdp = mgdp.drop(['a'], axis=1)

In [108]:
# mgdp = mgdp.drop([0])

In [109]:
# mgdp['Time']= pd.to_datetime(mgdp['Time'])

In [12]:
mgdp = mGDP.set_index('Time', drop=True)
# mgdp = mgdp.set_index('Time')['Population'].resample('M').interpolate()

In [13]:
upsampled = mgdp.resample('M').mean().interpolate(method='linear')
print(upsampled[0:5])

            Personal income (thousands of dollars)  Population  \
Time
2002-01-31                             67107084.00  2315747.00
2002-02-28                             67284853.33  2317440.58
2002-03-31                             67462622.67  2319134.17
2002-04-30                             67640392.00  2320827.75
2002-05-31                             67818161.33  2322521.33

            Per capita income
Time
2002-01-31           28979.00
2002-02-28           29034.08
2002-03-31           29089.17
2002-04-30           29144.25
2002-05-31           29199.33

In [14]:
mgdp

,Personal income (thousands of dollars),Population,Per capita income
Time,,,
2002-01-01,67107084,2315747,28979
2003-01-01,69240316,2336070,29640
2004-01-01,74881769,2358684,31747
2005-01-01,81381738,2385872,34110
2006-01-01,89240479,2405911,37092
2007-01-01,92614163,2415576,38340
2008-01-01,93033991,2436062,38190
2009-01-01,85787430,2463943,34817
2010-01-01,95805838,2507065,38214
2011-01-01,100148724,2569856,38971
2012-01-01,103220841,2602184,39667
2013-01-01,103504316,2635640,39271
2014-01-01,111907652,2660389,42064
2015-01-01,119434694,2688156,44430
2016-01-01,119576094,2722574,43920
2017-01-01,131241442,2744878,47813
2018-01-01,138138976,2761581,50022

In [15]:
upsampled

,Personal income (thousands of dollars),Population,Per capita income
Time,,,
2002-01-31,67107084.00,2315747.00,28979.00
2002-02-28,67284853.33,2317440.58,29034.08
2002-03-31,67462622.67,2319134.17,29089.17
2002-04-30,67640392.00,2320827.75,29144.25
2002-05-31,67818161.33,2322521.33,29199.33
2002-06-30,67995930.67,2324214.92,29254.42
2002-07-31,68173700.00,2325908.50,29309.50
2002-08-31,68351469.33,2327602.08,29364.58
2002-09-30,68529238.67,2329295.67,29419.67
2002-10-31,68707008.00,2330989.25,29474.75
2002-11-30,68884777.33,2332682.83,29529.83
2002-12-31,69062546.67,2334376.42,29584.92
2003-01-31,69240316.00,2336070.00,29640.00
2003-02-28,69710437.08,2337954.50,29815.58
2003-03-31,70180558.17,2339839.00,29991.17
2003-04-30,70650679.25,2341723.50,30166.75
2003-05-31,71120800.33,2343608.00,30342.33
2003-06-30,71590921.42,2345492.50,30517.92
2003-07-31,72061042.50,2347377.00,30693.50
2003-08-31,72531163.58,2349261.50,30869.08
2003-09-30,73001284.67,2351146.00,31044.67
2003-10-31,73471405.75,2353030.50,31220.25
2003-11-30,73941526.83,2354915.00,31395.83
2003-12-31,74411647.92,2356799.50,31571.42
2004-01-31,74881769.00,2358684.00,31747.00
2004-02-29,75423433.08,2360949.67,31943.92
2004-03-31,75965097.17,2363215.33,32140.83
2004-04-30,76506761.25,2365481.00,32337.75
2004-05-31,77048425.33,2367746.67,32534.67
2004-06-30,77590089.42,2370012.33,32731.58
2004-07-31,78131753.50,2372278.00,32928.50
2004-08-31,78673417.58,2374543.67,33125.42
2004-09-30,79215081.67,2376809.33,33322.33
2004-10-31,79756745.75,2379075.00,33519.25
2004-11-30,80298409.83,2381340.67,33716.17
2004-12-31,80840073.92,2383606.33,33913.08
2005-01-31,81381738.00,2385872.00,34110.00
2005-02-28,82036633.08,2387541.92,34358.50
2005-03-31,82691528.17,2389211.83,34607.00
2005-04-30,83346423.25,2390881.75,34855.50
2005-05-31,84001318.33,2392551.67,35104.00
2005-06-30,84656213.42,2394221.58,35352.50
2005-07-31,85311108.50,2395891.50,35601.00
2005-08-31,85966003.58,2397561.42,35849.50
2005-09-30,86620898.67,2399231.33,36098.00
2005-10-31,87275793.75,2400901.25,36346.50
2005-11-30,87930688.83,2402571.17,36595.00
2005-12-31,88585583.92,2404241.08,36843.50
2006-01-31,89240479.00,2405911.00,37092.00
2006-02-28,89521619.33,2406716.42,37196.00
2006-03-31,89802759.67,2407521.83,37300.00
2006-04-30,90083900.00,2408327.25,37404.00
2006-05-31,90365040.33,2409132.67,37508.00
2006-06-30,90646180.67,2409938.08,37612.00
2006-07-31,90927321.00,2410743.50,37716.00
2006-08-31,91208461.33,2411548.92,37820.00
2006-09-30,91489601.67,2412354.33,37924.00
2006-10-31,91770742.00,2413159.75,38028.00
2006-11-30,92051882.33,2413965.17,38132.00
2006-12-31,92333022.67,2414770.58,38236.00
2007-01-31,92614163.00,2415576.00,38340.00
2007-02-28,92649148.67,2417283.17,38327.50
2007-03-31,92684134.33,2418990.33,38315.00
2007-04-30,92719120.00,2420697.50,38302.50
2007-05-31,92754105.67,2422404.67,38290.00
2007-06-30,92789091.33,2424111.83,38277.50
2007-07-31,92824077.00,2425819.00,38265.00
2007-08-31,92859062.67,2427526.17,38252.50
2007-09-30,92894048.33,2429233.33,38240.00
2007-10-31,92929034.00,2430940.50,38227.50
2007-11-30,92964019.67,2432647.67,38215.00
2007-12-31,92999005.33,2434354.83,38202.50
2008-01-31,93033991.00,2436062.00,38190.00
2008-02-29,92430110.92,2438385.42,37908.92
2008-03-31,91826230.83,2440708.83,37627.83
2008-04-30,91222350.75,2443032.25,37346.75
2008-05-31,90618470.67,2445355.67,37065.67
2008-06-30,90014590.58,2447679.08,36784.58
2008-07-31,89410710.50,2450002.50,36503.50
2008-08-31,88806830.42,2452325.92,36222.42
2008-09-30,88202950.33,2454649.33,35941.33
2008-10-31,87599070.25,2456972.75,35660.25
2008-11-30,86995190.17,2459296.17,35379.17
2008-12-31,86391310.08,2461619.58,35098.08
2009-01-31,85787430.00,2463943.00,34817.00
2009-02-28,86622297.33,2467536.50,35100.08
2009-03-31,87457164.67,2471130.00,35383.17
2009-04-30,88292032.00,2474723.50,35666.25
2009-05-31,89126899.33,2478317.00,35949.33
2009-06-30,89961766.67,2481910.50,36232.42
2009-07-31,90796634.00,2485504.00,36515.50
2009-08-31,91631501.33,2489097.50,36798.58
2009-09-30,92466368.67,2492691.00,37081.67
2009-10-31,93301236.00,2496284.50,37364.75
2009-11-30,94136103.33,2499878.00,37647.83
2009-12-31,94970970.67,2503471.50,37930.92
2010-01-31,95805838.00,2507065.00,38214.00
2010-02-28,96167745.17,2512297.58,38277.08
2010-03-31,96529652.33,2517530.17,38340.17
2010-04-30,96891559.50,2522762.75,38403.25
2010-05-31,97253466.67,2527995.33,38466.33
2010-06-30,97615373.83,2533227.92,38529.42
2010-07-31,97977281.00,2538460.50,38592.50
2010-08-31,98339188.17,2543693.08,38655.58
2010-09-30,98701095.33,2548925.67,38718.67
2010-10-31,99063002.50,2554158.25,38781.75
2010-11-30,99424909.67,2559390.83,38844.83
2010-12-31,99786816.83,2564623.42,38907.92
2011-01-31,100148724.00,2569856.00,38971.00
2011-02-28,100404733.75,2572550.00,39029.00
2011-03-31,100660743.50,2575244.00,39087.00
2011-04-30,100916753.25,2577938.00,39145.00
2011-05-31,101172763.00,2580632.00,39203.00
2011-06-30,101428772.75,2583326.00,39261.00
2011-07-31,101684782.50,2586020.00,39319.00
2011-08-31,101940792.25,2588714.00,39377.00
2011-09-30,102196802.00,2591408.00,39435.00
2011-10-31,102452811.75,2594102.00,39493.00
2011-11-30,102708821.50,2596796.00,39551.00
2011-12-31,102964831.25,2599490.00,39609.00
2012-01-31,103220841.00,2602184.00,39667.00
2012-02-29,103244463.92,2604972.00,39634.00
2012-03-31,103268086.83,2607760.00,39601.00
2012-04-30,103291709.75,2610548.00,39568.00
2012-05-31,103315332.67,2613336.00,39535.00
2012-06-30,103338955.58,2616124.00,39502.00
2012-07-31,103362578.50,2618912.00,39469.00
2012-08-31,103386201.42,2621700.00,39436.00
2012-09-30,103409824.33,2624488.00,39403.00
2012-10-31,103433447.25,2627276.00,39370.00
2012-11-30,103457070.17,2630064.00,39337.00
2012-12-31,103480693.08,2632852.00,39304.00
2013-01-31,103504316.00,2635640.00,39271.00
2013-02-28,104204594.00,2637702.42,39503.75
2013-03-31,104904872.00,2639764.83,39736.50
2013-04-30,105605150.00,2641827.25,39969.25
2013-05-31,106305428.00,2643889.67,40202.00
2013-06-30,107005706.00,2645952.08,40434.75
2013-07-31,107705984.00,2648014.50,40667.50
2013-08-31,108406262.00,2650076.92,40900.25
2013-09-30,109106540.00,2652139.33,41133.00
2013-10-31,109806818.00,2654201.75,41365.75
2013-11-30,110507096.00,2656264.17,41598.50
2013-12-31,111207374.00,2658326.58,41831.25
2014-01-31,111907652.00,2660389.00,42064.00
2014-02-28,112534905.50,2662702.92,42261.17
2014-03-31,113162159.00,2665016.83,42458.33
2014-04-30,113789412.50,2667330.75,42655.50
2014-05-31,114416666.00,2669644.67,42852.67
2014-06-30,115043919.50,2671958.58,43049.83
2014-07-31,115671173.00,2674272.50,43247.00
2014-08-31,116298426.50,2676586.42,43444.17
2014-09-30,116925680.00,2678900.33,43641.33
2014-10-31,117552933.50,2681214.25,43838.50
2014-11-30,118180187.00,2683528.17,44035.67
2014-12-31,118807440.50,2685842.08,44232.83
2015-01-31,119434694.00,2688156.00,44430.00
2015-02-28,119446477.33,2691024.17,44387.50
2015-03-31,119458260.67,2693892.33,44345.00
2015-04-30,119470044.00,2696760.50,44302.50
2015-05-31,119481827.33,2699628.67,44260.00
2015-06-30,119493610.67,2702496.83,44217.50
2015-07-31,119505394.00,2705365.00,44175.00
2015-08-31,119517177.33,2708233.17,44132.50
2015-09-30,119528960.67,2711101.33,44090.00
2015-10-31,119540744.00,2713969.50,44047.50
2015-11-30,119552527.33,2716837.67,44005.00
2015-12-31,119564310.67,2719705.83,43962.50
2016-01-31,119576094.00,2722574.00,43920.00
2016-02-29,120548206.33,2724432.67,44244.42
2016-03-31,121520318.67,2726291.33,44568.83
2016-04-30,122492431.00,2728150.00,44893.25
2016-05-31,123464543.33,2730008.67,45217.67
2016-06-30,124436655.67,2731867.33,45542.08
2016-07-31,125408768.00,2733726.00,45866.50
2016-08-31,126380880.33,2735584.67,46190.92
2016-09-30,127352992.67,2737443.33,46515.33
2016-10-31,128325105.00,2739302.00,46839.75
2016-11-30,129297217.33,2741160.67,47164.17
2016-12-31,130269329.67,2743019.33,47488.58
2017-01-31,131241442.00,2744878.00,47813.00
2017-02-28,131816236.50,2746269.92,47997.08
2017-03-31,132391031.00,2747661.83,48181.17
2017-04-30,132965825.50,2749053.75,48365.25
2017-05-31,133540620.00,2750445.67,48549.33
2017-06-30,134115414.50,2751837.58,48733.42
2017-07-31,134690209.00,2753229.50,48917.50
2017-08-31,135265003.50,2754621.42,49101.58
2017-09-30,135839798.00,2756013.33,49285.67
2017-10-31,136414592.50,2757405.25,49469.75
2017-11-30,136989387.00,2758797.17,49653.83
2017-12-31,137564181.50,2760189.08,49837.92
2018-01-31,138138976.00,2761581.00,50022.00

In [94]:
upsampled

Time
2002-01-31    NaN
2002-02-28    NaN
2002-03-31    NaN
2002-04-30    NaN
2002-05-31    NaN
2002-06-30    NaN
2002-07-31    NaN
2002-08-31    NaN
2002-09-30    NaN
2002-10-31    NaN
2002-11-30    NaN
2002-12-31    NaN
2003-01-31    NaN
2003-02-28    NaN
2003-03-31    NaN
2003-04-30    NaN
2003-05-31    NaN
2003-06-30    NaN
2003-07-31    NaN
2003-08-31    NaN
2003-09-30    NaN
2003-10-31    NaN
2003-11-30    NaN
2003-12-31    NaN
2004-01-31    NaN
2004-02-29    NaN
2004-03-31    NaN
2004-04-30    NaN
2004-05-31    NaN
2004-06-30    NaN
2004-07-31    NaN
2004-08-31    NaN
2004-09-30    NaN
2004-10-31    NaN
2004-11-30    NaN
2004-12-31    NaN
2005-01-31    NaN
2005-02-28    NaN
2005-03-31    NaN
2005-04-30    NaN
2005-05-31    NaN
2005-06-30    NaN
2005-07-31    NaN
2005-08-31    NaN
2005-09-30    NaN
2005-10-31    NaN
2005-11-30    NaN
2005-12-31    NaN
2006-01-31    NaN
2006-02-28    NaN
2006-03-31    NaN
2006-04-30    NaN
2006-05-31    NaN
2006-06-30    NaN
2006-07-31    NaN
2006-08-31    NaN
2006-09-30    NaN
2006-10-31    NaN
2006-11-30    NaN
2006-12-31    NaN
2007-01-31    NaN
2007-02-28    NaN
2007-03-31    NaN
2007-04-30    NaN
2007-05-31    NaN
2007-06-30    NaN
2007-07-31    NaN
2007-08-31    NaN
2007-09-30    NaN
2007-10-31    NaN
2007-11-30    NaN
2007-12-31    NaN
2008-01-31    NaN
2008-02-29    NaN
2008-03-31    NaN
2008-04-30    NaN
2008-05-31    NaN
2008-06-30    NaN
2008-07-31    NaN
2008-08-31    NaN
2008-09-30    NaN
2008-10-31    NaN
2008-11-30    NaN
2008-12-31    NaN
2009-01-31    NaN
2009-02-28    NaN
2009-03-31    NaN
2009-04-30    NaN
2009-05-31    NaN
2009-06-30    NaN
2009-07-31    NaN
2009-08-31    NaN
2009-09-30    NaN
2009-10-31    NaN
2009-11-30    NaN
2009-12-31    NaN
2010-01-31    NaN
2010-02-28    NaN
2010-03-31    NaN
2010-04-30    NaN
2010-05-31    NaN
2010-06-30    NaN
2010-07-31    NaN
2010-08-31    NaN
2010-09-30    NaN
2010-10-31    NaN
2010-11-30    NaN
2010-12-31    NaN
2011-01-31    NaN
2011-02-28    NaN
2011-03-31    NaN
2011-04-30    NaN
2011-05-31    NaN
2011-06-30    NaN
2011-07-31    NaN
2011-08-31    NaN
2011-09-30    NaN
2011-10-31    NaN
2011-11-30    NaN
2011-12-31    NaN
2012-01-31    NaN
2012-02-29    NaN
2012-03-31    NaN
2012-04-30    NaN
2012-05-31    NaN
2012-06-30    NaN
2012-07-31    NaN
2012-08-31    NaN
2012-09-30    NaN
2012-10-31    NaN
2012-11-30    NaN
2012-12-31    NaN
2013-01-31    NaN
2013-02-28    NaN
2013-03-31    NaN
2013-04-30    NaN
2013-05-31    NaN
2013-06-30    NaN
2013-07-31    NaN
2013-08-31    NaN
2013-09-30    NaN
2013-10-31    NaN
2013-11-30    NaN
2013-12-31    NaN
2014-01-31    NaN
2014-02-28    NaN
2014-03-31    NaN
2014-04-30    NaN
2014-05-31    NaN
2014-06-30    NaN
2014-07-31    NaN
2014-08-31    NaN
2014-09-30    NaN
2014-10-31    NaN
2014-11-30    NaN
2014-12-31    NaN
2015-01-31    NaN
2015-02-28    NaN
2015-03-31    NaN
2015-04-30    NaN
2015-05-31    NaN
2015-06-30    NaN
2015-07-31    NaN
2015-08-31    NaN
2015-09-30    NaN
2015-10-31    NaN
2015-11-30    NaN
2015-12-31    NaN
2016-01-31    NaN
2016-02-29    NaN
2016-03-31    NaN
2016-04-30    NaN
2016-05-31    NaN
2016-06-30    NaN
2016-07-31    NaN
2016-08-31    NaN
2016-09-30    NaN
2016-10-31    NaN
2016-11-30    NaN
2016-12-31    NaN
2017-01-31    NaN
2017-02-28    NaN
2017-03-31    NaN
2017-04-30    NaN
2017-05-31    NaN
2017-06-30    NaN
2017-07-31    NaN
2017-08-31    NaN
2017-09-30    NaN
2017-10-31    NaN
2017-11-30    NaN
2017-12-31    NaN
2018-01-31    NaN
Freq: M, Name: Population, dtype: object